/**
 * SmartAdvisor — Claude AI-powered thermal safety briefing panel.
 *
 * Uses fetch() with a streaming response to consume the SSE endpoint
 * POST /api/ai/explain and renders tokens as they arrive.
 */

import { useState } from 'react';

const USER_TYPES = ['Worker', 'Elderly', 'Child', 'Athlete', 'General public'];

const BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

export default function SmartAdvisor({ date, station, humidex, comfortClass }) {
  const [userType, setUserType] = useState('Worker');
  const [streaming, setStreaming] = useState(false);
  const [text, setText] = useState('');
  const [error, setError] = useState(null);

  async function startStream() {
    if (!date || !station || humidex == null) return;

    setStreaming(true);
    setError(null);
    setText('');

    try {
      const response = await fetch(`${BASE_URL}/api/ai/explain`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          date,
          station,
          humidex,
          comfort_class: comfortClass,
          user_type: userType,
        }),
      });

      if (!response.ok) {
        throw new Error(`API error ${response.status}`);
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop(); // keep incomplete last line

        for (const line of lines) {
          if (line.startsWith('data: ')) {
            const chunk = line.slice(6);
            if (chunk === '[DONE]') {
              setStreaming(false);
              return;
            }
            // Restore newlines that were escaped for SSE transport
            setText((prev) => prev + chunk.replace(/\\n/g, '\n'));
          }
        }
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setStreaming(false);
    }
  }

  const canFetch = date && station && humidex != null;

  return (
    <div className="bg-[#1a1f2e] border border-[#2d3548] rounded-xl p-5 space-y-4">
      <div className="flex items-center gap-2">
        <h3 className="text-[#f1f5f9] font-semibold">AI Smart Advisor</h3>
        <span className="text-xs text-[#94a3b8] bg-[#38bdf822] px-2 py-0.5 rounded-full border border-[#38bdf844]">
          Claude Sonnet
        </span>
      </div>

      <div className="flex gap-3">
        <div className="flex-1">
          <label className="text-[#94a3b8] text-xs block mb-1">User Type</label>
          <select
            value={userType}
            onChange={(e) => setUserType(e.target.value)}
            className="w-full bg-[#0f1117] border border-[#2d3548] rounded-lg text-[#f1f5f9] text-sm px-3 py-2 focus:outline-none focus:border-[#38bdf8]"
          >
            {USER_TYPES.map((t) => <option key={t} value={t}>{t}</option>)}
          </select>
        </div>

        <div className="flex items-end">
          <button
            onClick={startStream}
            disabled={streaming || !canFetch}
            className="bg-[#38bdf8] hover:bg-[#0ea5e9] text-[#0f1117] font-semibold rounded-lg px-4 py-2 text-sm transition-colors disabled:opacity-50"
          >
            {streaming ? 'Thinking...' : 'Ask Claude'}
          </button>
        </div>
      </div>

      {!canFetch && (
        <p className="text-[#94a3b8] text-xs">
          Select a station and date to request an AI briefing.
        </p>
      )}

      {error && <p className="text-[#ef4444] text-xs">{error}</p>}

      {/* Streaming output */}
      {(text || streaming) && (
        <div className="bg-[#0f1117] rounded-lg p-4 border border-[#2d3548] min-h-[80px]">
          <p className="text-[#f1f5f9] text-sm whitespace-pre-wrap leading-relaxed">
            {text}
            {streaming && (
              <span className="inline-block w-1 h-4 bg-[#38bdf8] ml-0.5 animate-pulse" />
            )}
          </p>
        </div>
      )}

      {text && !streaming && (
        <p className="text-[#94a3b8] text-[10px]">
          Generated by Claude Sonnet (claude-sonnet-4-20250514) &bull; BioSense360 AI Advisor
        </p>
      )}
    </div>
  );
}
